[admin-canary] WIP refactor cra3
nossas/bonde pull request #1100
Opened 2019-05-28 11:54 UTC by alalbux

## Contexto
Foi atualizado a versão do `create-react-app` removendo o eject criado na concepção do projeto e adicionando o `react-script@3.0.1`

Issue relacionada #1097 

## Checklist
- [ ] Atualiza o `build`, `test` e `dev` pro `react-scripts`

## Notas de deploy
Os testes não estão passando como deveriam. Foi removido o `ava`, ideia é refatorar de uma forma que use o mínimo de dependencias. 

## Como testar?
Testando os scripts no projeto

2019-05-29 16:20 UTC, lpirola requested changes
os commits em geral estão ótimo, é importante manter a forma de subir a aplicação em produção pois o Dockerfile desse package utiliza o npm start para subir o projeto e a única dependência dentro da imagem é o serve.

2019-05-29 16:20 UTC, lpirola commented on packages/bonde-admin-canary/package.json
> +    "test": "jest",
importante manter o start pois é a forma como funciona em produção

2019-05-31 14:39 UTC, rolivegab approved these changes

2019-05-31 21:01 UTC, lpirola approved these changes

2019-05-31 21:06 UTC, merged