Feature/lint config canary
nossas/bonde pull request #1213
Opened 2019-07-26 14:44 UTC by igr-santos

## Contexto

## Checklist
- [ ] Itens

## Issues linkadas
- [ ] Resolves #

## Screenshots

### Layout:
[insira o screenshot aqui]

### Preview:
[insira o screenshot aqui]

## Notas de deploy

## Como testar?

**Novos scripts**:

- `script` : detalhes do script

**Novas dependências**:

- `dependency` : detalhes da dependência

**Novas dependências de desenvolvedor**:

- `dependency` : detalhes da dependência

2019-07-26 21:26 UTC, alalbux commented
@rolivegab e @igr-santos os testes estão quebrando pq precisa fazer alguns ajustes tem 99 error no log, nao sei se atualizando a branch com a develop resolveria, mas é bom olhar. Tem algumas coisas que o codacy apontou também

2019-07-26 21:26 UTC, alalbux requested changes
Tá quebrando o build, precisa fazer alguns ajustes tem 99 error no log

2019-07-26 21:26 UTC, alalbux requested changes
Tá quebrando o build, precisa fazer alguns ajustes tem 99 error no log

2019-07-29 14:29 UTC, lpirola approved these changes

2019-07-29 14:56 UTC, merged