fix(plip): download pdf with file-saver
nossas/bonde pull request #1551
Opened 2022-02-07 19:44 UTC by igr-santos

## Contexto
Resolve download de arquivo PDF no formulário da PLIP 

## Como testar?

Testar em diferentes dispositivos, como smartphones Android e iOS e navegadores Chrome, Safari, Opera, Chrome e Firefox.

**Novas dependências**:

- [file-saver](https://github.com/eligrey/FileSaver.js)

2022-02-07 19:49 UTC, lpirola requested changes
Não estamos usando o yarn por padrão nos projetos, algum motivo especial para adicioná-lo? Exceto por isso, foi ótimo ver o trabalho de download ser tercerizado para outra biblioteca pois ela resolve exatamente os problema de compatibilidade que estávamos enfrentando, como descrito no readme da bibliote.ca

2022-02-07 19:53 UTC, igr-santos commented
> Não estamos usando o yarn por padrão nos projetos, algum motivo especial para adicioná-lo? Exceto por isso, foi ótimo ver o trabalho de download ser tercerizado para outra biblioteca pois ela resolve exatamente os problema de compatibilidade que estávamos enfrentando, como descrito no readme da bibliote.ca

tenho não, não me recordava estarmos usando apenas NPM

2022-02-08 17:09 UTC, gloriateodoro approved these changes

2022-02-08 17:31 UTC, lpirola approved these changes

2022-02-08 17:31 UTC, merged