Feature intl remaining pages
nossas/bonde pull request #857
Opened 2017-10-17 16:46 UTC by gabrielrtakeda

# Related issues
- Translate Mobilization Templates Pages #600
- Translate Donation Widget Pages #601
- Translate Form Widget Pages #602

# How to test
O ideal é fazer um teste geral em toda a aplicação pra garantir que não há nenhum erro e que todo o conteúdo esteja traduzido... Criei um novo arquivo `intl/locale-data/en.js` com a tradução temporária das chaves do arquivo `intl/locale-data/pt-BR.js` que o idioma padrão, apenas pra que o teste de garantia de tradução completa seja possível...

2017-10-25 10:22 UTC, gabrielrtakeda commented
# Test List: Another Pages
- [ ] (admin) /account/edit
- [ ] (admin) /account/retrieve
- [ ] (admin) /bot
- [ ] (admin) /login
- [ ] (admin) /register
- [ ] (public) /subscriptions/:id/edit

2017-10-25 10:22 UTC, gabrielrtakeda commented
# Test List: Pressure Widget Pages
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/autofire
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/email
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/finish

2017-10-25 10:22 UTC, gabrielrtakeda commented
# Test List: Form Widget Pages
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/autofire
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/export
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/fields
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/finish

2017-10-25 10:22 UTC, gabrielrtakeda commented
# Test List: Donation Widget Pages
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/autofire
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/export
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/finish

2017-10-25 10:22 UTC, gabrielrtakeda commented
# Test List: Mobilization Templates Pages
- [ ] (admin) /mobilizations/templates/list
- [ ] (admin) /mobilizations/:mobilization_id/templates/choose
- [ ] (admin) /mobilizations/:mobilization_id/templates/choose/custom
- [ ] (admin) /mobilizations/:mobilization_id/templates/choose/global
- [ ] (admin) /mobilizations/:mobilization_id/templates/create

2017-10-25 10:22 UTC, gabrielrtakeda commented
# Test List: Mobilizations Pages
- [ ] (admin) /mobilizations
- [ ] (admin) /mobilizations/new
- [ ] (admin) /mobilizations/:mobilization_id/analytics
- [ ] (admin) /mobilizations/:mobilization_id/basics
- [ ] (admin) /mobilizations/:mobilization_id/blocks/create
- [ ] (admin) /mobilizations/:mobilization_id/customDomain
- [ ] (admin) /mobilizations/:mobilization_id/edit
- [ ] (admin) /mobilizations/:mobilization_id/launch
- [ ] (admin) /mobilizations/:mobilization_id/launch/end
- [ ] (admin) /mobilizations/:mobilization_id/metrics
- [ ] (admin) /mobilizations/:mobilization_id/sharing

2017-10-25 10:22 UTC, gabrielrtakeda commented
# Test List: Community Pages
- [ ] (admin) /community
- [ ] (admin) /community/domain
- [ ] (admin) /community/domain/add
- [ ] (admin) /community/info
- [ ] (admin) /community/invite
- [ ] (admin) /community/mailchimp
- [ ] (admin) /community/new
- [ ] (admin) /community/recipient
- [ ] (admin) /community/report
- [ ] (admin) /community/twilio

2017-10-26 16:11 UTC, gabrielrtakeda commented
# Acceptance Test List
Lista de testes de aceitação (staging) com base nas rotas do sistema

### Rotas de Minha Conta
- [ ] (admin) /login
- [ ] (admin) /register
- [ ] (admin) /account/retrieve
- [ ] (admin) /account/edit
- [ ] (public) /subscriptions/:id/edit

### Rotas de Comunidades
- [ ] (admin) /community
- [ ] (admin) /community/domain
- [ ] (admin) /community/domain/add
- [ ] (admin) /community/info
- [ ] (admin) /community/invite
- [ ] (admin) /community/mailchimp
- [ ] (admin) /community/new
- [ ] (admin) /community/recipient
- [ ] (admin) /community/report
- [ ] (admin) /community/twilio

### Rotas de Mobilizações
- [ ] (admin) /mobilizations
- [ ] (admin) /mobilizations/new
- [ ] (admin) /mobilizations/:mobilization_id/analytics
- [ ] (admin) /mobilizations/:mobilization_id/basics
- [ ] (admin) /mobilizations/:mobilization_id/blocks/create
- [ ] (admin) /mobilizations/:mobilization_id/customDomain
- [ ] (admin) /mobilizations/:mobilization_id/edit
- [ ] (admin) /mobilizations/:mobilization_id/launch
- [ ] (admin) /mobilizations/:mobilization_id/launch/end
- [ ] (admin) /mobilizations/:mobilization_id/metrics
- [ ] (admin) /mobilizations/:mobilization_id/sharing

### Rotas de Templates de mobilização
- [ ] (admin) /mobilizations/templates/list
- [ ] (admin) /mobilizations/:mobilization_id/templates/create
- [ ] (admin) /mobilizations/:mobilization_id/templates/choose
- [ ] (admin) /mobilizations/:mobilization_id/templates/choose/custom
- [ ] (admin) /mobilizations/:mobilization_id/templates/choose/global

### Rotas de Widget de Doação
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/autofire
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/export
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/finish

### Rotas de Widget de Formulário
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/autofire
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/export
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/fields
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/finish

### Rotas de Widget de Pressão
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/autofire
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/email
- [ ] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/finish

2017-11-05 22:52 UTC, lpirola requested changes
@gabrielrtakeda tem um arquivo que não está mergeado.

@pedrotorres92 assim que for resolvido você já pode testar.

2017-11-06 13:32 UTC, pedrotorres92 commented
beleza, quando puder me marca no pivotal! 

@gabrielrtakeda @lpirola

2017-11-06 15:03 UTC, gabrielrtakeda commented
@lpirola provavelmente entrou alguma coisa pra develop, devido a isso, por sorte só 1 arquivo tava dando conflito... Dei rebase e resolvi na mão.. Agora é só aguardar o [build no CI](https://ci.bonde.org/nossas/bonde-client/530) terminar pra testar em staging..

2017-11-06 20:11 UTC, pedrotorres92 commented
@gabrielrtakeda, só uma correção no "How to test", no Mac pra trocar o idioma do Chrome precisa trocar o idioma do sistema. Sobre o teste, vou colocar lá no Pivotal.

2017-11-07 18:07 UTC, pedrotorres92 commented
Fala @gabrielrtakeda, vou tentar fazer um post aqui pra indicar todos os erros que eu peguei de uma maneira mais visual e que você entenda o fluxo, e respondo no pivotal com o link daqui, só pra seguir atualizando sempre lá também.

# **Começando do início:**

## Coisas mais gerais

- Tem uns erros conceituais de tradução. Tipo, em alguns lugares, BONDE tá sendo traduzido como "Tram". É uma marca, não pode ser traduzido, tipo em "Create Community":
![screen shot 2017-11-07 at 14 16 15](https://user-images.githubusercontent.com/33130068/32506995-52809b94-c3cd-11e7-9dba-f7f71fc240b3.png)

- Assim como o "footer do BONDE" tá traduzido. Não sei se vale pensar em outra frase, mas "Made to cause" é meio ruim. Acho que vale bater com a Maju.
![screen shot 2017-11-07 at 14 36 48](https://user-images.githubusercontent.com/33130068/32509380-46f876c8-c3d4-11e7-8a6f-532d84ece073.png)


- Tem algumas coisas de UX, tipo o "to exchange" no painel de controle, aparece cortado: 
![screen shot 2017-11-06 at 18 59 21](https://user-images.githubusercontent.com/33130068/32506598-230444b6-c3cc-11e7-8274-42592eb1f929.png)

- No "Create Community", no texto de ajuda da cidade, tá "first name". Não faz muito sentido, tem que ser "City name":
![screen shot 2017-11-07 at 14 16 15](https://user-images.githubusercontent.com/33130068/32506995-52809b94-c3cd-11e7-9dba-f7f71fc240b3.png)

## Mobilizações 

- Na aba pra convidar mobilizadores para a mobilização, no texto de ajuda tem um e-mail que tá "mobilizador@email.com". É uma besteirinha, mas se a gente tá querendo que tudo seja em inglês, acho que vale mudar: ![screen shot 2017-11-06 at 18 59 08](https://user-images.githubusercontent.com/33130068/32506722-78fbbb7e-c3cc-11e7-85f0-97f2eb2d41be.png)

- No Community Settings, na aba "Mailchimp", os dois botões tão sem tradução (salvar e sincronizar):
![screen shot 2017-11-06 at 18 59 33](https://user-images.githubusercontent.com/33130068/32506784-9c560e94-c3cc-11e7-9567-2f15597fce45.png)

- Em "New Mobilization", quando escolhemos "Template", só a opção "My templates" aparece traduzida. O "Template Guia" e o "Do zero" seguem em PT.
![screen shot 2017-11-07 at 14 21 22](https://user-images.githubusercontent.com/33130068/32507088-abc85b7e-c3cd-11e7-8913-fea23f38c6a6.png)

- Quando a mobilização é criada, todos os blocos criados aparecem na aba de cima como "Bloco 1, 2, 3...". Deveria aparecer como "Block 1, 2, 3..."
![screen shot 2017-11-07 at 14 22 47](https://user-images.githubusercontent.com/33130068/32507137-cf2f979e-c3cd-11e7-896e-d5a35e985895.png)

### Formulário de Pressão

- O Counter Text do formulário de pressão, quando habilitado, aparece o texto "pressões feitas" em português como defaut:
![screen shot 2017-11-07 at 14 27 14](https://user-images.githubusercontent.com/33130068/32507174-ebde98ea-c3cd-11e7-9482-3bfa3dc1d04f.png)

- No "Email to Target" do formulário de pressão, o texto de ajuda da box "Targets" aparece todo em português, com "Email do primeiro alvo..."
![screen shot 2017-11-07 at 14 28 05](https://user-images.githubusercontent.com/33130068/32507212-11a58944-c3ce-11e7-9eeb-f688abe08940.png)

- Quando eu desejo remover um widget, qualquer que seja, o pop-up abre em português: 
![screen shot 2017-11-07 at 14 30 40](https://user-images.githubusercontent.com/33130068/32507248-2592edca-c3ce-11e7-99bf-510085b03ed5.png)

### Widget de texto 

- O Widget de texto está todo em português, os botões "salvar" e toda as edições de imagem dentro dele, como nas duas imagens:
![screen shot 2017-11-07 at 14 55 23](https://user-images.githubusercontent.com/33130068/32507448-94a5e578-c3ce-11e7-82a3-76b6e8cab4f3.png)
![screen shot 2017-11-07 at 14 55 45](https://user-images.githubusercontent.com/33130068/32507470-a1c2639e-c3ce-11e7-811a-bb8e25a80cc5.png)

### Widget de doação: 
- O texto de ajuda da deadline tá com o formato de data br e não com o americano: 
![screen shot 2017-11-07 at 14 32 02](https://user-images.githubusercontent.com/33130068/32507805-a1a2a684-c3cf-11e7-8626-8c425aa824bc.png)
- No mesmo espaço, você pode colocar uma data anterior ao dia de hoje como "data final". Isso deveria ser padronizado para sempre uma data depois, já que não faz sentido a meta já ter passado, entende? 
![screen shot 2017-11-07 at 14 35 24](https://user-images.githubusercontent.com/33130068/32509204-cac02722-c3d3-11e7-8c49-4b72c7b0d992.png)

- Nos valores, alguns textos de ajuda estão com $ ao invés de R$. Vale padronizar tudo pra R$, já que só aceitamos em Real.
![screen shot 2017-11-07 at 14 32 17](https://user-images.githubusercontent.com/33130068/32507844-ba0f2ca6-c3cf-11e7-8c69-2d5a6b8e533e.png)
- Tem um espaço a mais entre o R e o $ no texto que fala sobre os boletos custarem R$ 3,00. 
![screen shot 2017-11-07 at 14 33 08](https://user-images.githubusercontent.com/33130068/32507972-04d5e4d2-c3d0-11e7-8224-8cf1fdb65344.png)

### Set Mobilization & Share Mobilization

- No Set Mobilization Domain, o texto de ajuda do subdomain tá em português também, com "nomedamob..."
![screen shot 2017-11-07 at 14 42 00](https://user-images.githubusercontent.com/33130068/32509511-a53dc3f0-c3d4-11e7-8424-258d3dd91438.png)

- O tweet text default do share mobilization tá em português. O ideal seria traduzir:
![screen shot 2017-11-07 at 14 43 17](https://user-images.githubusercontent.com/33130068/32509593-e4365978-c3d4-11e7-8308-711b9747b855.png)

- Todos os dropdowns dos "Primary Domains" tão com "Escolha" ao invés de "Choose".
![screen shot 2017-11-07 at 14 44 51](https://user-images.githubusercontent.com/33130068/32509629-fd35260c-c3d4-11e7-8961-5ccdd9a06156.png)

2017-11-22 16:04 UTC, lpirola approved these changes

2017-11-22 21:48 UTC, merged

2017-11-24 17:04 UTC, pedrotorres92 commented
Fala Gabriel!

Explicando o reject por aqui: 

## Formulários

Não sei o que aconteceu, se tá dando conflito com o upload da atualização dos formulários feitos pelo @igr-santos em ambiente de staging, mas todos os forms estão sem tradução pelo menos na "aba principal"
### Pressão
![screen shot 2017-11-24 at 14 55 34](https://user-images.githubusercontent.com/33130068/33219158-fd4ef23e-d127-11e7-8761-e558684aff8c.png)

### Ação (inscrição) 
![screen shot 2017-11-24 at 14 56 17](https://user-images.githubusercontent.com/33130068/33219159-fd6966f0-d127-11e7-9061-edbb68e12ba2.png)

### Doação
O de doação ainda tem um texto de outra aba que tá sem tradução também: 
![screen shot 2017-11-24 at 14 57 03](https://user-images.githubusercontent.com/33130068/33219160-fd9d7404-d127-11e7-9be0-abb764d462f2.png)

De resto, tá tudo certo!