Feature import activists on crm
nossas/bonde pull request #865
Opened 2017-10-24 13:33 UTC by igr-santos

## How to test

1. Open `/activists` page
2. Click on `Importar CSV` button
3. Upload csv file with `first_name`, `last_name` and `email` like header

2017-10-26 14:45 UTC, lpirola requested changes
Existem alguns arquivos que não estão mergeados com o develop.

2017-10-26 17:17 UTC, gabrielrtakeda requested changes

2017-10-26 17:17 UTC, gabrielrtakeda commented on routes/admin/authenticated/sidebar/activists/component/import-csv.js
> +          message: `${result.length} ativistas importados com sucesso.`,
@igr-santos, esquema seria já incluir a tradução no nosso fluxo de desenvolvimento, pra que não aconteça de ter textos não traduzidos... agora que eu tô vendo esses lances de tradução, ficou bem claro pra mim que é muito mais difícil corrigir algo que não tá traduzido depois de implementado e tals... no caso dessa linha, ao invés de definir a chave `id` da tradução direto no objeto de configuração do `notify()`, o esquema seria já passar esse texto traduzido pro objeto da notificação... você pode fazer algo como os arquivos de exemplo abaixo:

- [arquivo de objetos de configuração do `notify()`](https://github.com/nossas/bonde-client/blob/feature-intl-remaining-pages/client/utils/notifications.js#L55-L58)
- [arquivo que repassa o objeto `intl`](https://github.com/nossas/bonde-client/blob/feature-intl-remaining-pages/routes/admin/authenticated/sidebar/widgets-pressure-settings/email/page.connected.js#L17)
- [adicionar as chaves no arquivo de tradução](https://github.com/nossas/bonde-client/blob/feature-intl-remaining-pages/intl/locale-data/pt-BR.js#L121-L122)

2017-10-26 17:17 UTC, gabrielrtakeda commented on client/utils/validate/index.js
> +  message: 'Required field.'
Traduzir

2017-10-26 17:17 UTC, gabrielrtakeda commented on routes/admin/authenticated/sidebar/activists/container.js
> +                      {totalCount} pessoas
Traduzir usando plurarization do `react-intl`...

Exemplos:
- [chave no arquivo de tradução](https://github.com/nossas/bonde-client/blob/feature-intl-remaining-pages/intl/locale-data/pt-BR.js#L1321-L1326)
- [uso da chave no componente](https://github.com/nossas/bonde-client/blob/feature-intl-remaining-pages/client/mobilizations/widgets/__plugins__/pressure/components/target-list/index.js#L60-L69)

2017-10-26 17:17 UTC, gabrielrtakeda commented on routes/admin/authenticated/sidebar/activists/container.js
> +                    <button type='button'>Importar CSV</button>
Traduzir

2017-10-26 17:17 UTC, gabrielrtakeda commented on routes/admin/authenticated/sidebar/activists/container.js
>                        Exportar CSV
Traduzir

2017-10-26 17:23 UTC, gabrielrtakeda commented
A funcionalidade em tá rolando lindamente.. Fiz um teste importando um arquivo `.csv` com 30 linhas e foi sucesso! Segue print:

<img width="697" alt="screen shot 2017-10-26 at 15 01 18" src="https://user-images.githubusercontent.com/5435389/32067311-838025ae-ba61-11e7-94b4-c1fa664e802d.png">

2017-10-26 18:48 UTC, igr-santos commented
@lpirola e @gabrielrtakeda atualizado com as correções solicitadas

2017-10-31 13:08 UTC, lpirola approved these changes

2017-10-31 13:14 UTC, merged